### ISSUE TITLE
Problem with having number in hostname

### ISSUE THREAD

**Issue by mgolshan** [christianalfoni/create-ssl-certificate#9]
Maybe this could work better:
```
  if (typeof text !== 'string' || !text.match(/^[a-zA-Z\-0-9]+$/)) {
    console.error(colors.red + `You did not pass in a valid hostname`)
    process.exit(1)
  }
```

**Comment by christianalfoni** [comment]
Oh, yeah, that makes sense. You wanna create PR on it to make the suggestion official? 😄

**Comment by mgolshan** [comment]
@christianalfoni Sure.
Created.
https://github.com/christianalfoni/create-ssl-certificate/pull/12
